FROM arm32v7/debian:bullseye-slim

# Install required packages and directories
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3=3.9.2-3 python3-pip=20.3.4-4+deb11u1 \
        python3-libcamera python3-kms++ \
        python3-prctl libatlas-base-dev ffmpeg libopenjp2-7 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoremove \
    && mkdir /usr/src/app \
    && mkdir /usr/src/app/birdy_files \
    && mkdir /usr/src/app/birdy_files/images

# Application source
WORKDIR /usr/src/app
ADD . /usr/src/app/

# Install application dependencies
RUN python3 -m pip install -r requirements.txt

# Run the birdy_watcher
CMD ["python3","birdy_watcher.py"]